### ISSUE TITLE
Tests hang on ecl

### ISSUE THREAD

**Issue by jgarte** [Lisp-Stat/special-functions#4]
Hi,

Tests are hanging at this stage on ecl:

```
Running test suite ALL-TESTS
 Running test suite INCOMPLETE-GAMMA
```

Is that to be expected?

**Comment by Symbolics** [comment]
Lisp-Stat has only been tested on SBCL.

**Comment by snunez1** [comment]
@jgarte, did you get this test working on ECL?

**Comment by jgarte** [comment]
> @jgarte, did you get this test working on ECL?

Nope, tests are still disabled:

https://git.savannah.gnu.org/cgit/guix.git/tree/gnu/packages/lisp-xyz.scm?id=master#n27206
