### ISSUE TITLE
sign-gamma

### ISSUE THREAD

**Issue by Saint-Even** [Lisp-Stat/special-functions#5]
Hello, 
I'm stymied on quickload of lisp-stat. It might actually be a problem and not me. I've been digging in the stack trace for a few hours. Here's context ask for anything else, Im new to CL so not sure what you need to isolate.
ubuntu 20.04.06
sbcl
spacemacs
slime

The crux is in gamma.lisp, at the sign-gamma definition. There's a comparison (eq x double-float-nan) which is causing this error.
arithmetic error FLOATING-POINT-INVALID-OPERATION signalled
Operation was (> #<DOUBLE-FLOAT quiet NaN> #<DOUBLE-FLOAT quiet NaN>).
    [Condition of type FLOATING-POINT-INVALID-OPERATION]

New to CL so my environment should be somewhat suspect, but I have had other programs load and run from quicklisp/asdf. including cephes. Portions of stat lisp are able to be quickloaded separately, but not those which have any dependency on the gamma.lisp file

Thanks for this excellent software I look forward to spreading it and contributing

**Comment by Saint-Even** [comment]
Operation was... edited by the upload filters haha
let H be hash, A be angle braces open and close
operation was (> **HA**DOUBLE-FLOAT QUIET NaN**A** **HA** DOUBLE-FLOAT quiet NaN**A**)

**Comment by snunez1** [comment]
What version of SBCL are you running? `(lisp-implementation-version)` will show you this.

Possibly related: https://www.reddit.com/r/lisp/comments/1ce2a5c/sbcl_debugger_invoked_on_a/

**Comment by Saint-Even** [comment]
sbcl 1.5.4
This is the version that is avail from 'conda install sbcl'
on double checking conda-forge I see sbcl v2.4.0 there. I will try to make a more isolated environment and test sbcl as I add the other components of my dev env. Instinct says some other conda install demoted the version. 

https://github.com/brown/protobuf/issues/21
This issues stack trace is almost identical to the the error I am seeing. I suspect that some quality about the nan implementation or something nearby is at play. I don't have enough experience with sbcl (yet) to untangle it though. 
Very much appreciate how fast you got back on this, and its likely you nailed it as a version issue first try.

**Comment by Saint-Even** [comment]
conda update sbcl
v -> 2.2.11
retry quickload, same error
full quit/restart spacemacs
new image in slime
quickload straight to success

Thank you Snunez
